config/routes.rb
Blogr::Engine.routes.draw do
  resources :configurations

  resources :sessions
  resources :users do
    member do
      get 'dashboard'
    end
  end
  resources :posts
  root 'posts#index'
end

app/models/blogr/post.rb
module Blogr
  class Post < ActiveRecord::Base
    # Callbacks
    before_save :update_status

    # Scopes
    scope :published, -> { where(published: true) }

    # Associations
    belongs_to :user

    # Methods
    def slug
      title.downcase.gsub(" ", "-")
    end

    def to_param
      "#{id}-#{slug}"
    end

    def update_status
      if published && published_at.nil?
        self.published_at = DateTime.now
      elsif published == false
        self.published_at = nil
      end
    end

    def status
      if published then "Published" else "Draft" end
    end
  end
end

app/models/blogr/user.rb
module Blogr
  class User < ActiveRecord::Base
    has_secure_password

    # Associations
    has_many :posts

    # Validations
    validates :name, :email, presence: true
    validates :name, uniqueness: true
    validates :email, uniqueness: true
  end
end

app/controllers/blogr/application_controller.rb
module Blogr
  class ApplicationController < ActionController::Base
    before_filter :authorize, :set_meta

    def set_meta(title="", description="", keyowrds="")
      @meta_title = if title != "" then title else Blogr.meta_title end
      @meta_description = if description != "" then title else Blogr.meta_description end
      @meta_keywords = if keyowrds != "" then title else Blogr.meta_keywords end
    end

    private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
      redirect_to root_url, alert: "Not authorized!" if current_user.nil?
    end

    def is_admin?
      true if current_user
    end
    helper_method :is_admin?
  end
end

app/controllers/blogr/posts_controller.rb
require_dependency "blogr/application_controller"

module Blogr
  class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    skip_before_filter :authorize, only: [:show, :index]

    # GET /posts
    def index
      @posts = Post.published

      respond_to do |format|
        format.html
        format.rss { render :layout => false }
      end
    end

    # GET /posts/1
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    def create
      @post = current_user.posts.build(post_params)

      if @post.save
        redirect_to @post, notice: 'Post was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /posts/1
    def update
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to root_url, notice: 'Post was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def post_params
        params.require(:post).permit(:title, :text, :user_id, :published)
      end
  end
end

app/controllers/blogr/sessions_controller.rb
require_dependency "blogr/application_controller"

module Blogr
  class SessionsController < ApplicationController
    skip_before_filter :authorize, only: [:new, :create]

    def new
    end

    def create
      user = User.find_by_email(params[:email])

      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to dashboard_user_path(current_user), notice: "Logged in!"
      else
        flash[:error] = "Email or password is invalid."
        render :new
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to root_url, notice: "Logged out!"
    end
  end
end

app/controllers/blogr/users_controller.rb
require_dependency "blogr/application_controller"

module Blogr
  class UsersController < ApplicationController
    skip_before_filter :authorize, only: [:new, :create] # DELETE this line once you've created your first author

    def dashboard
      @users = User.all
      @posts = Post.all
    end

    def new
      @user = User.new
    end

    def edit
      @user = current_user
    end

    def create
      @user = User.new(user_params)

      if @user.save
        session[:user_id] = @user.id
        redirect_to dashboard_user_path(@user), notice: "New author created!"
      else
        render :new
      end
    end

    def update
      @user = User.find(params[:id])

      if @user.update(user_params)
        redirect_to dashboard_user_path(@user), notice: 'Author updated.'
      else
        render :edit
      end
    end

    private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/helpers/blogr/application_helper.rb
module Blogr
  module ApplicationHelper
  end
end

app/helpers/blogr/posts_helper.rb
module Blogr
  module PostsHelper
  end
end

app/helpers/blogr/sessions_helper.rb
module Blogr
  module SessionsHelper
  end
end

app/helpers/blogr/users_helper.rb
module Blogr
  module UsersHelper
  end
end

app/views/blogr/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render "blogr/shared/form_errors", object: @post %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :published, "Publish?" %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogr/posts/_post.html.erb
<h2><%= link_to "#{post.title}", post %></h2>
<small>by <%= post.user.name %> <%= "on #{post.published_at.strftime("%Y")}" if post.published_at %></small>
<br>
<%= post.text %>
<% if is_admin? %>
  <hr>
  <%= link_to 'Edit', edit_post_path(post) %>
  |
  <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<hr>

app/views/blogr/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', root_path %>

app/views/blogr/posts/index.html.erb
<h1>Listing posts</h1>

<%= render @posts %>

app/views/blogr/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/blogr/posts/show.html.erb
<h1><%= @post.title %></h1>
<small>by <%= @post.user.name %> <%= "on #{@post.published_at.strftime("%d %b, %Y")}" if @post.published_at %></small>

<p><%= @post.text %></p>

<hr>
<% if is_admin? %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', root_path %>

app/views/blogr/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <% if object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(object.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/blogr/shared/_nav.html.erb
<% if current_user %>
  Author: <%= current_user.name %>
  |
  <%= link_to 'Home', root_url %>
  |
  <%= link_to 'Dashboard', dashboard_user_path(current_user) %>
  |
  <%= link_to 'New Post', new_post_path %>
  |
  <%= link_to "Log out", session_path(current_user), method: "delete" %>
<% else %>
  <%= link_to 'Home', root_url %>
  |
  <%= link_to "Log in", new_session_path %>
<% end %>
<hr>

app/views/blogr/shared/_notice.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, id: "flash_#{name}" %>
<% end %>

app/views/blogr/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "blogr/shared/form_errors", object: @user %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/blogr/users/_posts.html.erb
<% @posts.each do |post| %>
  <tr>
    <td><%= link_to "#{post.title}", post %></td>
    <td><%= post.user.name %></td>
    <td><%= post.status %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/blogr/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.posts.count %></td>
  <% if user == current_user %>
    <td><%= link_to "Edit", edit_user_path(current_user) %></td>
  <% end %>
</tr>

app/views/blogr/users/dashboard.html.erb
<h1><%= current_user.name.pluralize %> Dashboard</h1>

<div class="section">
  <h2>Authors</h2>
  <table>
    <tr>
      <th>Author</th>
      <th>Email</th>
      <th>Posts</th>
      <th></th>
    </tr>
    <%= render @users %>
    <tr><td colspan="4"><%= link_to "Add Author", new_user_path %></td></tr>
  </table>
  <hr>
</div>

<div class="section">
  <h2>Posts</h2>
  <table>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th colspan="2"></th>
    </tr>
    <%= render "posts" %>
    <tr><td colspan="5"><%= link_to 'New Post', new_post_path %></td></tr>
  </table>
  <hr>
</div>

app/views/blogr/users/edit.html.erb
<h1>Edit Author</h1>
<%= render "form" %>

app/views/blogr/users/new.html.erb
<h1>New Author</h1>
<%= render "form" %>

app/views/layouts/blogr/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @meta_title %></title>
  <meta name="description" content="<%= @meta_description %>">
  <meta name="description" content="<%= @meta_keywords %>">
  <%= stylesheet_link_tag    "blogr/application", media: "all" %>
  <%= javascript_include_tag "blogr/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= auto_discovery_link_tag(:rss, root_url) %>
  <%= render "blogr/shared/nav" %>
  <%= render "blogr/shared/notice" %>
  <%= yield %>

</body>
</html>